resources:
  - resources/istio.yaml
  - resources/net-istio.yaml
  - resources/peerAuth.yaml
  - resources/knative-ingress-gateway.yaml
  - resources/auth.yaml

patchesStrategicMerge:
  - resources/delete-gateway.yaml