apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: argocd/overlays/dev/knative-serving
    repoURL: https://github.com/ZEISS/EventHub
    targetRevision: HEAD
  sources: []
  project: default