apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: custom-http-target
  namespace: testservices
spec:
  template:
    metadata:
      labels:
        app: custom-http-target
    spec:
      containers:
        - image: ghcr.io/zeiss/eventhub/custom-http-service:2.0.0
        #- image: dev.local/custom-http-service:1.0.0
          name: custom-http-target
          env:
            - name: K_SINK
              value: https://webhook.site/298ae7a3-f50e-43b7-bc35-961be47bb155